### PR TITLE
Make livenessprobe configurable

### PR DESCRIPTION
**Pull request by Dutchy-**
Our ECR is too big, so the livenessProbe failed before the server was ready. I had to put in a livenessProbe initial delay to make it work for us :)

### CODE REVIEW

**Comment by Dutchy-** [comment]
Note that I don't know how to test edits to a helm chart, but I copied everything from securityContext as an example so I hope it's good :)

**Comment by js-timbirkett** [comment]
I thought this might eventually come up... How many ECR repos do you have? Currently there are 2 open issues on the ECR exporter that I want to look at:
- https://github.com/aws-exporters/ecr/issues/8
- https://github.com/aws-exporters/ecr/issues/9

**Comment by Dutchy-** [comment]
thanks @js-timbirkett - we currently have over 600 ECR repositories. I don't think we're hitting any pagination issues yet but we might hit that eventually :)

**Comment by js-timbirkett** [comment]
Thanks @Dutchy- - I've just released chart version `0.2.4` which uses ecr exporter version `0.1.4` - this moves things around a bit so that the collector no longer blocks on startup. metrics are now available as they are added rather than blocking while all the data is collected from AWS so there is no need for long initial delays, which result in slow deployments.

**Pull request merged**
